POST https://api.service-kp.com/oauth2/device?grant_type=device_code&client_id=xbmc&client_secret=cgg3gtifu46urtfp2zp1nqtba0k2ezxh


# {
#   "code": "jq7egf3ml3ulnp8zw7pzx3i8bpgz7ybq",
#   "user_code": "75B95",
#   "verification_uri": "https://kino.pub/device",
#   "interval": 5,
#   "expires_in": 300
# }
###

POST https://api.service-kp.com/oauth2/device?grant_type=device_token&client_id=xbmc&client_secret=cgg3gtifu46urtfp2zp1nqtba0k2ezxh&code=jq7egf3ml3ulnp8zw7pzx3i8bpgz7ybq
##

@accessToken=q0bdivhxvo5wb2eats3fcu07k405lshq
# {
#   "access_token": "4iku3ixfd653xudmd2gj62lbnevd90s3",
#   "refresh_token": "gu443hesc2javc9lhwb241obohg71000",
#   "expires_in": 86400
# }
####



GET https://api.service-kp.com/v1/items/search?q=south park&access_token={{accessToken}}
###

@basePath=https://api.service-kp.com/v1
@southParkId=8634
###

GET {{basePath}}/items/46330?access_token=7wy92hrqultiv5s8lgzqev722nvj4cdn
Accept: application/json

